# Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK]       
 set_property IOSTANDARD LVCMOS33 [get_ports CLK]
 create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK]
#seven-segment LED display
set_property PACKAGE_PIN W7 [get_ports Led_Out[6]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports Led_Out[6]]
set_property PACKAGE_PIN W6 [get_ports Led_Out[5]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports Led_Out[5]]
set_property PACKAGE_PIN U8 [get_ports Led_Out[4]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports Led_Out[4]]
set_property PACKAGE_PIN V8 [get_ports Led_Out[3]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports Led_Out[3]]
set_property PACKAGE_PIN U5 [get_ports Led_Out[2]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports Led_Out[2]]
set_property PACKAGE_PIN V5 [get_ports Led_Out[1]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports Led_Out[1]]
set_property PACKAGE_PIN U7 [get_ports Led_Out[0]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports Led_Out[0]]
    
set_property PACKAGE_PIN U2 [get_ports AnodeOut[0]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports AnodeOut[0]]
set_property PACKAGE_PIN U4 [get_ports AnodeOut[1]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports AnodeOut[1]]
set_property PACKAGE_PIN V4 [get_ports AnodeOut[2]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports AnodeOut[2]]
set_property PACKAGE_PIN W4 [get_ports AnodeOut[3]]                    
    set_property IOSTANDARD LVCMOS33 [get_ports AnodeOut[3]]